travis:
  secure:
    BINSTAR_TOKEN: DmvteaPxcWKRRA4nVX4uK4Ih6ZX7CqJtdvqis4nkkB/etXLcj6hpm4EypeFHjK3u/hbqPH7stgSeyrXxkT+LnitefjylnHvZKOW1OfMReWT8ij/29vNf+Wbz9w5hYmavW1dHS7XocLiyUZ/pl3xQnRW3MVD+P0auDyBXg+Myao8Kz9s5u2iJgF0FXAsmtMAyUprYuw7AGrmHYr3lm5UbhWjQ4osBlFRDqu7iIn1ZxX9100fYonRAxL52IJRfXcZIWRNDhIVx+VLfAyvb4x0AoPoBOq9NLrOFiPfUa8+dAzi9uECGZoJrDllqQrtlYt1dB2OMS3Ge+nlWmDEDM8vv4e36iShARZNm9q2wQueoCQi9dCl+Lab+FSkgJ6dmU6gVv162dH7CFKvY2KYppikC7YY/TpENkdRRY7Ua5T5oShkmsAQiIKrAg03aa8LNFa1eWFhfkVaqrmhirWwHPfiM6NMv1CwdLinjeK2y0NQmcss0VTacMPEDIDOvlrFvj29m1GITV/hOH5T6eQFUN4YvFV/M3tkbbAcWMywGnQBdGJdcSEljRS4aUjJl/zuDQX9QxxqgB2kutoHtwLUNaEbEHzWlr/1YltOUObTrv6JOrUUgkWNI8VCjInmpTVKLRCNup1lR1hER2sKKU7VI2bQAtyFQSbr/P/x5yVEjodbTqxs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
